
## This analysis report (28 Apr 2025)

-   The goal of this analysis report is to provide a description of the data for analysis. Variables needed are described in the [SAP](https://docs.google.com/document/d/1GPIzetmxAJxbsQnpXG5_sj9buN0inlTDNljtyg4V1vE/edit?usp=sharing).

Some variables are not yet defined in precise terms, and may warrant discussion:

-   **Aim 1 requires**

    -   CAM-S scores, before and after consensus, in total BASIL-II sample

    -   Indicator for membership in clinical assessor reliability study (n = 46)

    -   Separate ratings for pre vs post consensus meeting

    -   Characteristics for description of the sample:

        -   Age

        -   Sex

        -   Εducation

        -   English as a first language

        -   Vision impairment

        -   Hearing impairment

        -   Depressive symptoms (PHQ)

        -   Cognitive performance (MoCA)

        -   Dementia (reference standard) *do we mean gold standard? \\rnj*

        -   AD-8

        -   ADL dependence

        -   IADL difficulties

        -   Delirium (reference standard) *do we mean gold standard? \\rnj*

    -   Characteristics to model selection into reliability study (***TBD*** right now planning on using the factors listed above, but really should be 4-5 predictors)

        -   **ACTION**: Need to generate VDSs for ADL and IADL characteristics

        -   **ACTION**: Replace REDCap PHQ, MoCA, and AD-8 summary measures with VDS versions

-   **Aim 2 additionally requires**

    -   Individual delirium features (inattention, disorganized thinking, altered level of consciousness, disorientation, memory impairment, perceptual disturbances, psychomotor agitation, psychomotor retardation, altered sleep-wake, inappropriate behavior, delusions)

        -   **ACTION**: Need to modify vds for CAM-S to generate and save individual indicators for the CAM features (0/1)

-   **Aim 3 additionally requires**

    -   "pre-acute" cognitive status

    -   patient group (really, study site) three distinct study sites: (1) acute medical inpatients; (2) scheduled surgical inpatients, and (3) long-term and post-acute care residents

    -   informant (family member/friend, nurse, CNA),

    -   pre-acute depression

***Note:*** **None of the aim 3 variables are pulled**: these need to be defined more precisely (i.e., with respect to REDCap data collected). All I can see in that list that can be consistently measured across site is, `site` itself. \\rnj

