```{r}
#   +-------------------------------------------------------------+
#   | Characteristics                      Setting                |
#   |                                  -----------------          |
#   |                              Medical   Surgical  Nursing    |
#   |                              (N = 10)  (N = 14)  home (N=22)|
#   +-------------------------------------------------------------+
#   | Age, M (SD)                  M (SD)    M (SD)    M (SD)     |
#   |                                                             |
#   | Sex, N (%)                                                  |
#   |   Women                    N (%)     N (%)     N (%)        |
#   |   Men                      N (%)     N (%)     N (%)        |
#   |                                                             |
#   | Education (years), M (SD)  M (SD)    M (SD)    M (SD)       |
#   |                                                             |
#   | English as 1st language    N (%)     N (%)     N (%)        |
#   |                                                             |
#   | Vision impairment          N (%)     N (%)     N (%)        |
#   |                                                             |
#   | Hearing impairment         N (%)     N (%)     N (%)        |
#   |                                                             |
#   | Depressive symptoms        M (SD)    M (SD)    M (SD)       |
#   | (PHQ), M (SD)                                               |
#   |                                                             |
#   | Cognitive performance      M (SD)    M (SD)    M (SD)       |
#   | (MoCA), M (SD)                                              |
#   |                                                             |
#   | Dementia (ref. std.),      N (%)     N (%)     N (%)        |
#   | N (%)                                                       |
#   |                                                             |
#   | AD-8, median (IQI)         Median    Median    Median       |
#   |                                                             |
#   | ADL dependence             Median    Median    Median       |
#   | (median, IQI)                                               |
#   |                                                             |
#   | IADL difficulties          Median    Median    Median       |
#   | (median, IQI)                                               |
#   |                                                             |
#   | Delirium (ref. std.),      N (%)     N (%)     N (%)        |
#   | N (%)                                                       |
#   +-------------------------------------------------------------+
#   
#   Notes: N’s are unweighted, but %, means, SD, medians and inter-
#   quartile intervals (IQI) reflect sampling weights.
#
#   Note as of 2025-04-30 ADL dependence and IADL difficulties are
#   not defined. 

```

```{r}
basil_df <- readRDS(here::here("RData", "046-basil_df.rds"))
n46 <- readRDS(here::here("RData", "030-n46.rds"))
```

# Table 1

```{r}
#| tbl-cap: "Descriptive statistics of the RS sample"
#| label: tbl-table1

basil_foo <- basil_df %>%
  filter(studyid %in% n46[["studyid"]]) %>%
  select(-studyid) %>%
  mutate(vdsite = factor(vdsite, levels = c(1, 2, 3), labels = c("BIDMC", "UF", "TNJH")),
         vdcci3 = car::recode(vdcharlson, "0 = 0; 1 = 1; 2:hi = 2"),
         vdcci3 = factor(vdcci3, levels = c(0, 1, 2), labels = c("0", "1", "2+"))
         ) %>%
  select(-vd_clinical_assessor, -vdsite2, -vdsite3, -w_eb, -w_lr, -vdcharlson) %>%
  select(
     vdsite,          vdage,           vdfemale,       vdnonwhite,     vdhisp,         vdesl,          vdeduc,         vdlivesalone,  
     vdmarried,       vdlivesinnh,     vdvisionimp,    vdhearingimp,   vdcci3,         vdmajneurogs,   vdminneurogs,   vddeliriumgs,   
     vddelseveritygs, vddemseveritygs, vdcamsrs,       phq_9_score,    moca_score,     ad8_total_score
  )





labelled::var_label(basil_foo$vdsite) <- "Site"
labelled::var_label(basil_foo$vdcci3) <- "Charlson Comorbidity Index"


basil_foo %>%
  labelled::to_factor() %>%
  gtsummary::tbl_summary(by = vdsite,
                         type = list(c(vdeduc) ~ "continuous"),
                         statistic = gtsummary::all_continuous() ~ "{mean} ({sd})") %>%
  gtsummary::add_overall()
```

```{r}
#| tbl-cap: "Descriptive statistics of the RS sample (weighted)"
#| label: tbl-table1-wt


basil_foo <- haven::zap_labels(basil_foo) 

survey::svydesign(~1, data = basil_foo, weights = ~w_eb) %>%
  gtsummary::tbl_svysummary(by = vdsite,
                            type = list(c(vdeduc) ~ "continuous"),
                            statistic = gtsummary::all_continuous() ~ "{mean} ({sd})") %>%
  gtsummary::add_overall()


```
