

```{r}

all_pairs_df_initial <- readRDS(here::here("RData", "050-all_pairs_df_initial.rds"))
all_pairs_df_consensus <- readRDS(here::here("RData", "050-all_pairs_df_consensus.rds"))
```

# Rater agreement

## Delirium severity

```{r}
#| label: tbl-delseverity-cross-pre
#| tbl-cap: "Crosstab of paired initial ratings of delirium severity"

all_pairs_df_initial %>%
  labelled::to_factor() %>%
  gtsummary::tbl_cross(delirium_severity_B, delirium_severity_A)
```

```{r}
#| label: fig-delseverity-heatmap-pre
#| fig-cap: "Heatmap showing agreement of paired initial ratings of delirium severity"

all_pairs_df_initial %>%
  filter(!is.na(delirium_severity_A), !is.na(delirium_severity_B)) %>%
  group_by(delirium_severity_A, delirium_severity_B) %>%
  summarize(n = n()) %>%
  ggplot(aes(x = delirium_severity_A, y = delirium_severity_B, fill = n)) +
    geom_tile() +
    scale_x_continuous("Delirium Severity (Rater A)", breaks = 0:10, minor_breaks = NULL) +
    scale_y_reverse("Delirium Severity (Rater B)", breaks = 0:10, minor_breaks = NULL) +
    scale_fill_viridis_c(
      option = "C",
      trans = scales::pseudo_log_trans(sigma = 1),
      breaks = c(1, 3, 10, 30, 100, 200),
      name = "Count"
    ) +
    coord_fixed() +
    hrbrthemes::theme_ipsum()



# ggplot2::ggplot(rs_pairs, aes(x = deliriumseverity_1nA, y = deliriumseverity_1nB)) +
#   geom_bin2d(binwidth = 1) +
#   scale_fill_viridis_c(
#     option = "C",
#     trans = scales::pseudo_log_trans(sigma = 1),
#     breaks = c(1, 3, 10, 30, 100, 200),
#     name = "Count"
#   ) +
#   coord_fixed() +
#   labs(
#     x = "Delirium Severity (Rater A)",
#     y = "Delirium Severity (Rater B)",
#     fill = "Count"
#   ) +
#   theme_minimal()
```


```{r}
#| label: tbl-delseverity-cross-post
#| tbl-cap: "Crosstab of paired consensus ratings of delirium severity"

all_pairs_df_consensus %>%
  labelled::to_factor() %>%
  gtsummary::tbl_cross(delirium_severity_B, delirium_severity_A)
```

```{r}
#| label: fig-delseverity-heatmap-post
#| fig-cap: "Heatmap showing agreement of paired ratings of delirium severity after consensus process"

all_pairs_df_consensus %>%
  filter(!is.na(delirium_severity_A), !is.na(delirium_severity_B)) %>%
  group_by(delirium_severity_A, delirium_severity_B) %>%
  summarize(n = n()) %>%
  ggplot(aes(x = delirium_severity_A, y = delirium_severity_B, fill = n)) +
    geom_tile() +
    scale_x_continuous("Delirium Severity (Rater A)", breaks = 0:10, minor_breaks = NULL) +
    scale_y_reverse("Delirium Severity (Rater B)", breaks = 0:10, minor_breaks = NULL) +
    scale_fill_viridis_c(
      option = "C",
      trans = scales::pseudo_log_trans(sigma = 1),
      breaks = c(1, 3, 10, 30, 100, 200),
      name = "Count"
    ) +
    coord_fixed() +
    hrbrthemes::theme_ipsum()

# ggplot2::ggplot(rs_pairs, aes(x = deliriumseverity_2nA, y = deliriumseverity_2nB)) +
#   geom_bin2d(binwidth = 1) +
#   scale_fill_viridis_c(
#     option = "C",
#     trans = scales::pseudo_log_trans(sigma = 1),
#     breaks = c(1, 3, 10, 30, 100, 200),
#     name = "Count"
#   ) +
#   coord_fixed() +
#   labs(
#     x = "Delirium Severity (Rater A)",
#     y = "Delirium Severity (Rater B)",
#     fill = "Count"
#   ) +
#   theme_minimal()
```


## Delirium presence

```{r}
#| label: tbl-delpresence-cross-pre
#| tbl-cap: "Crosstab of paired initial ratings of delirium presence"
all_pairs_df_initial %>%
  labelled::to_factor() %>%
  gtsummary::tbl_cross(delirium_presence_B, delirium_presence_A)
```


```{r}
#| label: tbl-delpresence-cross-post
#| tbl-cap: "Crosstab of paired consensus ratings of delirium presence"

all_pairs_df_consensus %>%
  labelled::to_factor() %>%
  gtsummary::tbl_cross(delirium_presence_B, delirium_presence_A)
```

## Dementia severity

```{r}
#| label: tbl-demseverity-cross-pre
#| tbl-cap: "Crosstab of paired initial ratings of dementia severity"

all_pairs_df_initial %>%
  labelled::to_factor() %>%
  gtsummary::tbl_cross(dementia_severity_B, dementia_severity_A)
```

```{r}
#| label: fig-demseverity-heatmap-pre
#| fig-cap: "Heatmap showing agreement of paired initial ratings of dementia severity"

all_pairs_df_initial %>%
  filter(!is.na(dementia_severity_A), !is.na(dementia_severity_B)) %>%
  group_by(dementia_severity_A, dementia_severity_B) %>%
  summarize(n = n()) %>%
  haven::zap_labels() %>%
  ggplot(aes(x = dementia_severity_A, y = dementia_severity_B, fill = n)) +
    geom_tile() +
    scale_x_continuous("Dementia Severity (Rater A)", breaks = 0:4, minor_breaks = NULL,
                       labels = c("No dementia", "Very mild", "Mild", "Moderate", "Severe")) +
    scale_y_reverse("Dementia Severity (Rater B)", breaks = 0:4, minor_breaks = NULL,
                       labels = c("No dementia", "Very mild", "Mild", "Moderate", "Severe")) +
    scale_fill_viridis_c(
      option = "C",
      trans = scales::pseudo_log_trans(sigma = 1),
      breaks = c(1, 3, 10, 30, 100, 200),
      name = "Count"
    ) +
    coord_fixed() +
    hrbrthemes::theme_ipsum()


```


```{r}
#| label: tbl-demseverity-cross-post
#| tbl-cap: "Crosstab of paired consensus ratings of dementia severity"
all_pairs_df_consensus %>%
  labelled::to_factor() %>%
  gtsummary::tbl_cross( dementia_severity_B, dementia_severity_A)
```

```{r}
#| label: fig-demseverity-heatmap-post
#| fig-cap: "Heatmap showing agreement of paired ratings of dementia severity after consensus process"

all_pairs_df_consensus %>%
filter(!is.na(dementia_severity_A), !is.na(dementia_severity_B)) %>%
  group_by(dementia_severity_A, dementia_severity_B) %>%
  summarize(n = n()) %>%
  haven::zap_labels() %>%
  ggplot(aes(x = dementia_severity_A, y = dementia_severity_B, fill = n)) +
    geom_tile() +
    scale_x_continuous("Dementia Severity (Rater A)", breaks = 0:4, minor_breaks = NULL,
                       labels = c("No dementia", "Very mild", "Mild", "Moderate", "Severe")) +
    scale_y_reverse("Dementia Severity (Rater B)", breaks = 0:4, minor_breaks = NULL,
                       labels = c("No dementia", "Very mild", "Mild", "Moderate", "Severe")) +
    scale_fill_viridis_c(
      option = "C",
      trans = scales::pseudo_log_trans(sigma = 1),
      breaks = c(1, 3, 10, 30, 100, 200),
      name = "Count"
    ) +
    coord_fixed() +
    hrbrthemes::theme_ipsum()


```

## NCD presence

```{r}
#| label: tbl-ncdpresence-cross-pre
#| tbl-cap: "Crosstab of paired initial ratings of NCD presence"

all_pairs_df_initial %>%
  labelled::to_factor() %>%
  gtsummary::tbl_cross(ncd_presence_B, ncd_presence_A)
```


```{r}
#| label: tbl-ncdpresence-cross-post
#| tbl-cap: "Crosstab of paired consensus ratings of NCD presence"

all_pairs_df_consensus %>%
  labelled::to_factor() %>%
  gtsummary::tbl_cross(ncd_presence_B, ncd_presence_A)
```
